# Project 2 - Global Space Economy Analysis

## Notebook 01: Build Database

**Objectives**
- Load the company database
- Inspect and clean the data
- Build an SQLite database
- Verify the database using SQL

In [26]:
import pandas as pd
import sqlite3

In [27]:
companies = pd.read_excel("../data/companies.xlsx")

companies.head()

             Company Ticker Country Listing Status          Sector Subsector
0             SpaceX   SPCX      US         Public  Infrastructure    Launch
1         Rocket Lab   RKLB      US         Public  Infrastructure    Launch
2        Blue Origin      -      US        Private  Infrastructure    Launch
3  Firefly Aerospace      -      US        Private  Infrastructure    Launch
4   Relativity Space      -      US        Private  Infrastructure    Launch

In [28]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company         83 non-null     object
 1   Ticker          83 non-null     object
 2   Country         83 non-null     object
 3   Listing Status  83 non-null     object
 4   Sector          83 non-null     object
 5   Subsector       83 non-null     object
dtypes: object(6)
memory usage: 4.0+ KB

In [29]:
companies.isnull().sum()

Company           0
Ticker            0
Country           0
Listing Status    0
Sector            0
Subsector         0
dtype: int64

In [30]:
companies.duplicated().sum()

np.int64(0)

In [31]:
conn = sqlite3.connect("../data/space_economy.db")

In [32]:
companies.to_sql(
    "companies",
    conn,
    if_exists="replace",
    index=False
)

83

In [33]:
pd.read_sql(
    "SELECT * FROM companies LIMIT 5;",
    conn
)

             Company Ticker Country Listing Status          Sector Subsector
0             SpaceX   SPCX      US         Public  Infrastructure    Launch
1         Rocket Lab   RKLB      US         Public  Infrastructure    Launch
2        Blue Origin      -      US        Private  Infrastructure    Launch
3  Firefly Aerospace      -      US        Private  Infrastructure    Launch
4   Relativity Space      -      US        Private  Infrastructure    Launch

In [34]:
pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

        name
0  companies

In [35]:
pd.read_sql(
    "PRAGMA table_info(companies);",
    conn
)

   cid            name  type  notnull dflt_value  pk
0    0         Company  TEXT        0       None   0
1    1          Ticker  TEXT        0       None   0
2    2         Country  TEXT        0       None   0
3    3  Listing Status  TEXT        0       None   0
4    4          Sector  TEXT        0       None   0
5    5       Subsector  TEXT        0       None   0

In [36]:
conn.close()